/* Generated by JTB 1.4.4 */
package qls.syntaxtree;

import qls.visitor.*;

public class CreateNew implements INode {

  public NodeToken f0;

  public NodeToken f1;

  public NodeChoice f2;

  private static final long serialVersionUID = 144L;

  public CreateNew(final NodeToken n0, final NodeToken n1, final NodeChoice n2) {
    f0 = n0;
    f1 = n1;
    f2 = n2;
  }

  public CreateNew(final NodeChoice n0) {
    f0 = new NodeToken("create");
    f1 = new NodeToken("new");
    f2 = n0;
  }

  public <R, A> R accept(final IRetArguVisitor<R, A> vis, final A argu) {
    return vis.visit(this, argu);
  }

  public <R> R accept(final IRetVisitor<R> vis) {
    return vis.visit(this);
  }

  public <A> void accept(final IVoidArguVisitor<A> vis, final A argu) {
    vis.visit(this, argu);
  }

  public void accept(final IVoidVisitor vis) {
    vis.visit(this);
  }

}
