/* Generated by JTB 1.4.4 */
package qls.visitor;

import qls.syntaxtree.*;

public interface IVoidVisitor {

  public void visit(final NodeList n);

  public void visit(final NodeListOptional n);

  public void visit(final NodeOptional n);

  public void visit(final NodeSequence n);

  public void visit(final NodeToken n);

  public void visit(final Start n);

  public void visit(final GlobalExpression n);

  public void visit(final CreateNew n);

  public void visit(final Use n);

  public void visit(final Main n);

  public void visit(final StatementExpression n);

  public void visit(final FieldDeclaration n);

  public void visit(final VariableDeclaration n);

  public void visit(final VariableAssign n);

  public void visit(final VariableValue n);

  public void visit(final GetFrom n);

  public void visit(final VariableName n);

  public void visit(final Proceed n);

  public void visit(final JavaStaticMethods n);

  public void visit(final IfExpression n);

  public void visit(final WhileExpression n);

  public void visit(final CmdExpression n);

  public void visit(final FuncExpression n);

  public void visit(final ReturnStatement n);

  public void visit(final MathExpression n);

  public void visit(final AdditiveExpression n);

  public void visit(final MultiplicativeExpression n);

  public void visit(final UnaryExpression n);

  public void visit(final RelationalExpression n);

  public void visit(final RelationalEqualityExpression n);

  public void visit(final RelationalGreaterExpression n);

  public void visit(final RelationalLessExpression n);

  public void visit(final UnaryRelational n);

  public void visit(final Identifier n);

  public void visit(final MyInteger n);

}
