/* Generated by JTB 1.4.4 */
package qls.syntaxtree;

import qls.visitor.*;

public class Start implements INode {

  public NodeListOptional f0;

  public NodeToken f1;

  public NodeListOptional f2;

  public Main f3;

  public NodeListOptional f4;

  public NodeToken f5;

  private static final long serialVersionUID = 144L;

  public Start(final NodeListOptional n0, final NodeToken n1, final NodeListOptional n2, final Main n3, final NodeListOptional n4, final NodeToken n5) {
    f0 = n0;
    f1 = n1;
    f2 = n2;
    f3 = n3;
    f4 = n4;
    f5 = n5;
  }

  public Start(final NodeListOptional n0, final NodeListOptional n1, final Main n2, final NodeListOptional n3) {
    f0 = n0;
    f1 = new NodeToken("me");
    f2 = n1;
    f3 = n2;
    f4 = n3;
    f5 = new NodeToken("end");
  }

  public <R, A> R accept(final IRetArguVisitor<R, A> vis, final A argu) {
    return vis.visit(this, argu);
  }

  public <R> R accept(final IRetVisitor<R> vis) {
    return vis.visit(this);
  }

  public <A> void accept(final IVoidArguVisitor<A> vis, final A argu) {
    vis.visit(this, argu);
  }

  public void accept(final IVoidVisitor vis) {
    vis.visit(this);
  }

}
