/* Generated by JTB 1.4.4 */
package qls.visitor;

import qls.syntaxtree.*;

public interface IRetVisitor<R> {

  public R visit(final NodeList n);

  public R visit(final NodeListOptional n);

  public R visit(final NodeOptional n);

  public R visit(final NodeSequence n);

  public R visit(final NodeToken n);

  public R visit(final Start n);

  public R visit(final GlobalExpression n);

  public R visit(final CreateNew n);

  public R visit(final Use n);

  public R visit(final Main n);

  public R visit(final StatementExpression n);

  public R visit(final FieldDeclaration n);

  public R visit(final VariableDeclaration n);

  public R visit(final VariableAssign n);

  public R visit(final VariableValue n);

  public R visit(final GetFrom n);

  public R visit(final VariableName n);

  public R visit(final Proceed n);

  public R visit(final JavaStaticMethods n);

  public R visit(final IfExpression n);

  public R visit(final WhileExpression n);

  public R visit(final CmdExpression n);

  public R visit(final FuncExpression n);

  public R visit(final ReturnStatement n);

  public R visit(final MathExpression n);

  public R visit(final AdditiveExpression n);

  public R visit(final MultiplicativeExpression n);

  public R visit(final UnaryExpression n);

  public R visit(final RelationalExpression n);

  public R visit(final RelationalEqualityExpression n);

  public R visit(final RelationalGreaterExpression n);

  public R visit(final RelationalLessExpression n);

  public R visit(final UnaryRelational n);

  public R visit(final Identifier n);

  public R visit(final MyInteger n);

}
